config/routes.rb
Rails.application.routes.draw do
  
  root 'main_pages#home' #Root path

  match '/home',    to: 'main_pages#home',    via: :get
  match '/about',   to: 'main_pages#about',   via: :get
  match '/contact', to: 'main_pages#contact', via: :get
  match '/attachments/download/:id', to: 'attachments#download', via: :get, as: 'download'

  match '/admin_feed', to: 'main_pages#admin_feed', via: :get
  match '/user/ban/:id', to: 'users#ban', as: :ban, via: :post
  match '/unban/:id', to: 'users#unban', as: :unban, via: :get
  match '/user/remove/:id', to: 'users#destroy', as: :remove_user, via: :delete
  match 'approve/:resource/:id', to: 'application#approve', as: :approve, via: :patch

  match '/search', to: 'searches#search', via: :get 

  devise_for :users, :skip => [:sessions], controllers: {registrations: 'registrations'}
  resources :users, only: [:index]
  as :user do
    get '/signin' => 'devise/sessions#new', :as => :new_user_session
    post '/signin' => 'devise/sessions#create', :as => :user_session
    match '/signout' => 'devise/sessions#destroy', :as => :log_out, :via => :delete
    match '/signout' => 'devise/sessions#destroy', :via => :get
  end

  match '/user/:username', to: 'users#show', as: :user, via: :get
  

  resources :users, only: [:index] do
    resources :friend_requests, only: [:create]
  end

  resources :friend_requests, only: [:destroy]
  resources :friendships, only: [:index, :create, :destroy]

  match '/like/:resource/:id', to: "likes#create", as: :like, via: :post
  match '/dislike/:resource/:id', to: "likes#destroy", as: :dislike, via: :delete
  match '/favourites', to: "likes#index", as: :favourites, via: :get

  concern :attachable do
    resources :attachments, only: [:create, :destroy]
  end

  resources :attachments, only: [:index, :new, :show, :create, :destroy] do
    resources :reports, only: [:new]
  end

  match '/course/:course_code', as: :course, to: 'courses#show', via: :get 

  resources :courses, only: [:new, :index, :create], concerns: [:attachable] do
    resources :enrollments, only: [:create]
  end

  resources :enrollments, only: [:index, :destroy] 

  resources :guides, only: [:new, :index, :create, :edit, :show, :update, :destroy], concerns: [:attachable] do
    resources :reports, only: [:new]
  end

  resources :reports, only: [:new, :show, :create, :destroy]

resources :messages, only: [:create]
resources :conversations, only: [:index, :show, :destroy] do
  member do
    post :reply
    post :trash
    post :untrash
    post :mark_as_read
  end

  collection do 
    delete :empty_trash
  end
end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index]
  helper_method :mailbox, :conversation


  def index
    @inbox = @mailbox.inbox.page(params[:ipage]).per(10)
    @trash = @mailbox.trash.page(params[:tpage]).per(10)
    @sent  = @mailbox.sentbox.page(params[:spage]).per(10)

    respond_to do |format|
      format.js
      format.html 
    end
  end

  def show 
    # @conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def trash
    flash[:notice] = 'Conversation moved to trash'
    @conversation.move_to_trash(current_user)
    redirect_to conversations_path
  end

  def untrash
    @conversation.untrash(current_user)
    redirect_to conversations_path
  end

  def destroy
    @conversation.receipts_for(current_user).destroy_all
    flash[:notice] = 'Conversation removed'
    redirect_to :conversations
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  # def mark_as_read
  #   @conversation.mark_as_read(current_user)
  #   flash[:success] = 'The conversation was marked as read.'
  #   redirect_to conversations_path
  # end

private 

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  # def show
  # end
  
  # def create
  #   recipient_usernames = conversation_params(:recipients).split(',')
  #   recipients = User.where(username: recipient_usernames).all

  #   conversation = current_user.
  #     send_message(recipients, *conversation_params(:body, :subject)).conversation

  #   redirect_to conversation_path(conversation)
  # end

  # def destroy
  #   conversation.mark_as_deleted(current_user)
  #   flash[:notice] = 'Conversation removed'
  #   redirect_to :conversations
  # end

  # def reply
  #   current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
  #   redirect_to conversation_path(conversation)
  # end

  # def trash
  #   conversation.move_to_trash(current_user)
  #   redirect_to :conversations
  # end

  # def untrash
  #   conversation.untrash(current_user)
  #   redirect_to :conversations
  # end

  # private

  # def mailbox
  #   @mailbox ||= current_user.mailbox
  # end

  # def conversation
  #   @conversation ||= mailbox.conversations.find(params[:id])
  # end

  # def conversation_params(*keys)
  #   fetch_params(:conversation, *keys)
  # end

  # def message_params(*keys)
  #   fetch_params(:message, *keys)
  # end

  # def fetch_params(key, *subkeys)
  #   params[key].instance_eval do
  #     case subkeys.size
  #     when 0 then self
  #     when 1 then self[subkeys.first]
  #     else subkeys.map{|k| self[k] }
  #     end
  #   end
  # end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_box.html.erb
<div class="message-box">
  <div class="col-md-12">
    <div class="panel-body">
      <ul class="chat">
        <% box.each do |c| %>
          <li class="left clearfix"><span class="chat-img pull-left">
            <% p = participant(c) %>
            <%= link_to (gravatar_for p, size: 100, class: 'img-circle'), user_path(username: p.username) %>
          </span>
            <div class="chat-body clearfix">
              <div class="header">
                  <strong class="primary-font"><%= link_to "#{p.username} | #{c.subject}", conversation_path(c) %>
                  </strong> 
                  <small class="text-muted">
                    <span class="fa fa-clock-o"></span>
                    <%= time_ago_in_words(c.last_message.updated_at) %>
                  </small>
                  <small class="pull-right">
                      <% unless c.is_trashed?(current_user) %>
                        <%= link_to trash_conversation_path(c), method: :post do %>
                          <i class="fa fa-trash" data-toggle="tooltip" title="Move to trash"></i>
                        <% end %>
                      <% else %>
                        <%= link_to untrash_conversation_path(c), method: :post do %>
                          <i class="fa fa-level-up" data-toggle="tooltip" title="Remove from trash"></i>
                        <% end %>
                      <% end %>
                    <%= link_to conversation_path(c), method: :delete do %>
                      <i class="fa fa-times" data-toggle="tooltip" title="Delete"></i>
                    <% end %>              
                  </small>
              </div>
              <p class="message-body">

                <b>Last message sent by 
                  <%= c.last_message.sender.username == p.username? ? p.username : 'you' %>:
                </b> 
                <%= truncate c.last_message.body, length: 200 %>
              </p>
            </div>
          </li>
          <% end %>
      </ul>
    </div>
    <div class="panel-footer">
      <div class="input-group">
          <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
          <span class="input-group-btn">
              <button class="btn btn-warning btn-sm" id="btn-chat">
                  Send</button>
          </span>
      </div>
    </div>
  </div> 
</div>

app/views/conversations/_new_message.html.erb
<div class="modal fade" id="new-message-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= "Send message to #{recipient.username}" %></h4>
      </div>
      <div class="modal-body">
        <div id="report-error-container">
          <%= render 'shared/errors', record: conversation %>  
        </div>
        <%= form_tag messages_path, method: :post do %>

        <div class="input">
          <%= text_field_tag 'message[subject', nil, placeholder: 'Enter message subject', id: 'subject', required: true, autofocus: true %>
          <label for="subject">Subject</label>
          <span class="help-block">Keep it simple (elaborate below)</span>
        </div>

        <div class="input">
          <%= text_area_tag 'message[body]', nil, placeholder: 'Your message...', id: 'msg', rows: 5 %>
          <label for="msg">Message</label>
           <%= hidden_field_tag 'recipient', recipient.id %>
        </div>
        
   
      <div class="modal-footer">
        <%= submit_tag 'Send Message', class: 'btn btn-primary', id: 'message-submit'%>
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= gravatar_for participant, size: 50 %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<div class="main-card">
<h2>Conversations</h2><hr>
  <div class="row" id="mailboxes-container">
    <div class="ui-tabgroup left-side icons-only">
      <input class="ui-tab1" type="radio" id="tgroup_b_tab1" name="tgroup_b" checked />
      <input class="ui-tab2" type="radio" id="tgroup_b_tab2" name="tgroup_b" />
      <input class="ui-tab3" type="radio" id="tgroup_b_tab3" name="tgroup_b" />
      <div class="ui-tabs">
        <label class="ui-tab1" for="tgroup_b_tab1" data-toggle="tooltip" title="Active" data-placement="left">
          <i class="fa fa-inbox"></i>
        </label>
        <label class="ui-tab2" for="tgroup_b_tab2" data-toggle="tooltip" title="Sent" data-placement="left">
          <i class="fa fa-send"></i>
        </label>
        <label class="ui-tab3" for="tgroup_b_tab3" data-toggle="tooltip" title="Trash" data-placement="left">
          <i class="fa fa-trash"></i>
        </label>
      </div>
      <div class="ui-panels">
        <div class="ui-tab1">
          <div class="row" id="inbox">
            <%= render 'box', box: @inbox %>
          </div>
          <div id="i-pag">
            <center><%= paginate @inbox, remote: true, param_name: 'ipage' %></center>
          </div>
        </div>

        <div class="ui-tab2">
          <div class="row" id="sentbox">
            <%= render 'box', box: @sent %> 
          </div>
          <div id="s-pag">
            <center><%= paginate @sent, remote: true, param_name: 'spage' %></center>
          </div>
        </div>
        <div class="ui-tab3">
          <div class="row" id="msg-trash">
            <%= render 'box', box: @trash %> 
          </div>
         <div id="t-pag">
            <center><%= paginate @trash, remote: true, param_name: 'tpage' %></center>
         </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/index.js.erb
//-- Inbox AJAX pagination
<% if @inbox.any? %>
  $('#i-pag').html("<center><%= j paginate @inbox, remote: true, param_name: 'ipage' %></center>");
  $('#inbox').html("<%= j render 'box', box: @inbox %>");
<% end %>

//-- Sentbox AJAX pagination
<% if @sent.any? %>
  $('#s-pag').html("<center><%= j paginate @sent, remote: true, param_name: 'spage' %></center>");
  $('#sentbox').html("<%= j render 'box', box: @sent %>");
<% end %>

//-- Trash AJAX pagination
<% if @trash.any? %>
  $('#t-pag').html("<center><%= j paginate @trash, remote: true, param_name: 'tpage' %></center>");
  $('#msg-trash').html("<%= j render 'box', box: @trash %>");
<% end %>

app/views/conversations/show.html.erb
<div class="main-card">
  <h2><%= @conversation.subject %></h2>

  <div class="conversation-container">
    <div class="timeline-centered">
    <% @conversation.receipts_for(current_user).each do |receipt| %>
      <% message = receipt.message %>
      <article class="timeline-entry">
        <div class="timeline-entry-inner">
          <div class="timeline-icon bg-success">
            <%= gravatar_for message.sender, size: 40 %>
          </div>

          <div class="timeline-label">
              <h2><%= link_to message.sender.name %> 
                <i class="fa fa-clock-o">&nbsp;&nbsp;</i><span><%= time_ago_in_words(message.created_at) %> ago</span>
              </h2>
              <blockquote>
                <%= message.body %>
              </blockquote>
          </div>
        </div>
      </article>
    <% end %>
      <article class="timeline-entry begin">
        <div class="timeline-entry-inner">
          <div class="timeline-icon" style="-webkit-transform: rotate(-90deg); -moz-transform: rotate(-90deg);">
              <i class="entypo-flight"></i> <a href="#" id="new-reply-trigger">+</a>
          </div>
        </div>
      </article>
    </div>
  </div>
  <div class="row" id="conversation-reply" hidden="true">
    <%= form_tag reply_conversation_path(@conversation), method: :post do %>
      <div class="input">
        <%= text_area_tag 'body', nil, placeholder: 'Reply...', id: 'msg', rows: 5, required: true %>
        <label for="msg">Message</label>
      </div>
      <%= submit_tag "Send Message", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>