config/routes.rb
Rails.application.routes.draw do
  
  root 'main_pages#home' #Root path

  match '/home',    to: 'main_pages#home',    via: :get
  match '/about',   to: 'main_pages#about',   via: :get
  match '/contact', to: 'main_pages#contact', via: :get
  match '/attachments/download/:id', to: 'attachments#download', via: :get, as: 'download'

  match '/admin_feed', to: 'main_pages#admin_feed', via: :get
  match '/user/ban/:id', to: 'users#ban', as: :ban, via: :post
  match '/unban/:id', to: 'users#unban', as: :unban, via: :get
  match '/user/remove/:id', to: 'users#destroy', as: :remove_user, via: :delete
  match 'approve/:resource/:id', to: 'application#approve', as: :approve, via: :patch

  match '/search', to: 'searches#search', via: :get 

  devise_for :users, :skip => [:sessions], controllers: {registrations: 'registrations'}
  resources :users, only: [:index]
  as :user do
    get '/signin' => 'devise/sessions#new', :as => :new_user_session
    post '/signin' => 'devise/sessions#create', :as => :user_session
    match '/signout' => 'devise/sessions#destroy', :as => :log_out, :via => :delete
    match '/signout' => 'devise/sessions#destroy', :via => :get
  end

  match '/user/:username', to: 'users#show', as: :user, via: :get
  

  resources :users, only: [:index] do
    resources :friend_requests, only: [:create]
  end

  resources :friend_requests, only: [:destroy]
  resources :friendships, only: [:index, :create, :destroy]

  match '/like/:resource/:id', to: "likes#create", as: :like, via: :post
  match '/dislike/:resource/:id', to: "likes#destroy", as: :dislike, via: :delete
  match '/favourites', to: "likes#index", as: :favourites, via: :get

  concern :attachable do
    resources :attachments, only: [:create, :destroy]
  end

  resources :attachments, only: [:index, :new, :show, :create, :destroy] do
    resources :reports, only: [:new]
  end

  match '/course/:course_code', as: :course, to: 'courses#show', via: :get 

  resources :courses, only: [:new, :index, :create], concerns: [:attachable] do
    resources :enrollments, only: [:create]
  end

  resources :enrollments, only: [:index, :destroy] 

  resources :guides, only: [:new, :index, :create, :edit, :show, :update, :destroy], concerns: [:attachable] do
    resources :reports, only: [:new]
  end

  resources :reports, only: [:new, :show, :create, :destroy]

resources :messages, only: [:create]
resources :conversations, only: [:index, :show, :destroy] do
  member do
    post :reply
    post :trash
    post :untrash
    post :mark_as_read
  end

  collection do 
    delete :empty_trash
  end
end

end

app/models/like.rb
class Like < ActiveRecord::Base
  #-- Associations
  belongs_to :likeable, polymorphic: true
  belongs_to :liker, class_name: "User"
  #-- Validations
  validates :liker_id, uniqueness: { scope: [:likeable_id, :likeable_type] }
  #-- Scopes
  scope :guides,      -> { where(likeable_type: "Guide") }
  scope :attachments, -> { where(likeable_type: "Attachment") }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def index
    @favourites = current_user.likes
    @guides = @favourites.where(likeable_type: "Guide").page(params[:gpage]).per(10)
    @attachments = @favourites.where(likeable_type: "Attachment").page(params[:apage]).per(10)
  end

  def create
    find_resource
    @like = current_user.likes.build
    @like.likeable = @resource
    if @like.save
      flash[:success] = "Added to your favourites. #{view_context.link_to 'View my favourites', favourites_path}"
    else
      flash[:error] = "Unable to add to favourites"
    end

    respond_to do |format|
      format.js
      format.html { redirect_to :back }
    end
  end

  def destroy
    find_resource
    @like = @resource.likes.where(liker_id: current_user.id)
    
    if @like.destroy_all
      flash[:success] = "Removed from favourites"
    else
      flash[:error] = "Unable to remove from favourites"
    end

    respond_to do |format|
      format.js
      format.html { redirect_to :back }
    end
  end

private

  def find_resource
    case params[:resource]
    when "guide"
      @resource = Guide.find params[:id]
    when "attachment"
      @resource = Attachment.find params[:id]
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/create.js.erb
  $('.like-btn.clicked').hide(); 
  $('.like-btn.clicked').attr("class","like-btn");
  $('.favourite').html("<%= j render 'shared/dislike_btn', resource: @resource %>");
  $('#flash-messages').html("<%= j render partial: 'shared/flash_messages', flash: flash %> ");
  <%= flash[:success] = nil %>
  <%= flash[:error] = nil %>
 // $('.liking-button-container').removeClass('clicked');
  

app/views/likes/destroy.js.erb
  $('.dislike-btn.clicked').hide();
  $('.dislike-btn.clicked').attr("class","dislike-btn");
  //alert($('.liking-button-container.clicked').attr('class'));
  $('.favourite').html("<%= j render 'shared/like_btn', resource: @resource %>");
  $('#flash-messages').html("<%= j render partial: 'shared/flash_messages', flash: flash %> ");
  //$('.liking-button-container').removeClass('clicked');
  <%= flash[:success] = nil %>
  <%= flash[:error] = nil %>

app/views/likes/index.html.erb
<div class="main-card">
  <h2>Favourites</h2>
 <div class="[ text-center nav nav-justified ]">
    <div class="row">
      <div class="col-md-12">
      <div class="tabbable-panel">
        <div class="tabbable-line">
          <ul class="nav nav-tabs ">
            <li class="active">
              <a href="#tab_default_1" data-toggle="tab">
              <h4 >Guides</h4> </a>
            </li>
            <li>
              <a href="#tab_default_2" data-toggle="tab">
              <h4 >Attachments</h4> </a>
            </li>
          </ul>
          
          <div class="tab-content">
            <div class="tab-pane active" id="tab_default_1">
              <div class="row friends-container">
              <% if @guides.any? %>
                <% @guides.each do |g| %>
                <div class="col-xs-6">
                  <div class="card">                
                    <div class="card-image"> 
                      <%= link_to (course_image g.likeable.course), course_path(course_code: g.likeable.course.course_code) %>
                    </div>
                    
                    <div class="card-info">
                      
                      <div class="name">
                        <p><%= link_to truncate(g.likeable.title,length: 80), guide_path(g.likeable) %></p> 
                      </div>
                      
                      <hr>
                      
                      <div class="content">
                        <p>
                          <b>Guide for:</b> 
                          <%= g.likeable.course.course_code %>
                        </p>
                        <p><b>Attachments:</b> <%= g.likeable.attachments.count %></p>
                      </div>
                    </div>
                  </div>    
                </div>
                <% end %>
              <% else %>
              
              No guides favourited yet. <%= link_to 'Find some', guides_path %>
  
              <% end %>

              </div> 
            </div>

            <div class="tab-pane" id="tab_default_2">
              <div class="row friends-container">
               <% if @attachments.any? %>
                <% @attachments.each do |a| %>
                  <div class="col-xs-6">
                    <div class="card">                
                       <div class="card-image"> 
                      <%= link_to attachment_icon_for(a.likeable), a.likeable %>
                    </div>
                    
                    <div class="card-info">
                      
                      <div class="name">
                        <p><%= link_to truncate(a.likeable.upload_file_name, length: 10),  a.likeable %></p> 
                      </div>
                      
                      <hr>
                      
                      <div class="content">
                        <p>
                          <b>For <%= a.likeable.attachable_type.downcase %>:</b> 
                          <% if a.likeable.attachable_type == "Course" %>  
                            <%= link_to a.likeable.attachable.course_code, course_path(course_code: a.likeable.attachable.course_code) %>
                          <% elsif a.likeable.attachable_type == "Guide" %>
                            <%= link_to a.likeable.attachable.title, a.likeable.attachable %>
                          <% end %>
                          <br>
                          <b>Uploader: </b> 
                          <%= link_to a.likeable.user.username, user_path(username: a.likeable.user.username) %>
                        </p>
                        <p data-no-turbolink><%= link_to download_path(id: a.likeable.id), class: 'btn btn-labeled btn-success' do %>
                          <span class="btn-label"><i class="fa fa-download"></i>&nbsp;<%= a.likeable.download_count %></span>
                          Download
                        <% end %></p>
                      
                      </div>
                    </div>
                  </div>    
                </div>
                <% end %>
              <% else %>
                No guides favourited yet. <%= link_to 'Find some', guides_path %> 
              <% end %>


              </div> 
            </div>  

          </div>
         </div>
        </div>
       </div>
      </div>    
</div>
</div>

app/views/likes/index.js.erb
//-- Guide AJAX pagination
<% if @guides.any? %>
  $('#g-pag').html("<center><%= j paginate @guides, remote: true, param_name: 'gpage' %></center>");
  $('#search-guides').html("<%= j render 'shared/guides', guides: @guides %>");
<% end %>

//-- Attachment AJAX pagination
<% if @attachments.any? %>
  $('#a-pag').html("<center><%= j paginate @attachments, remote: true, param_name: 'apage' %></center>");
  $('#search-attachments').html("<%= j render 'shared/attachments', attachments: @attachments %>");
<% end %>