config/routes.rb
Rails.application.routes.draw do
  
  root 'main_pages#home' #Root path

  match '/home',    to: 'main_pages#home',    via: :get
  match '/about',   to: 'main_pages#about',   via: :get
  match '/contact', to: 'main_pages#contact', via: :get
  match '/attachments/download/:id', to: 'attachments#download', via: :get, as: 'download'

  match '/admin_feed', to: 'main_pages#admin_feed', via: :get
  match '/user/ban/:id', to: 'users#ban', as: :ban, via: :post
  match '/unban/:id', to: 'users#unban', as: :unban, via: :get
  match '/user/remove/:id', to: 'users#destroy', as: :remove_user, via: :delete
  match 'approve/:resource/:id', to: 'application#approve', as: :approve, via: :patch

  match '/search', to: 'searches#search', via: :get 

  devise_for :users, :skip => [:sessions], controllers: {registrations: 'registrations'}
  resources :users, only: [:index]
  as :user do
    get '/signin' => 'devise/sessions#new', :as => :new_user_session
    post '/signin' => 'devise/sessions#create', :as => :user_session
    match '/signout' => 'devise/sessions#destroy', :as => :log_out, :via => :delete
    match '/signout' => 'devise/sessions#destroy', :via => :get
  end

  match '/user/:username', to: 'users#show', as: :user, via: :get
  

  resources :users, only: [:index] do
    resources :friend_requests, only: [:create]
  end

  resources :friend_requests, only: [:destroy]
  resources :friendships, only: [:index, :create, :destroy]

  match '/like/:resource/:id', to: "likes#create", as: :like, via: :post
  match '/dislike/:resource/:id', to: "likes#destroy", as: :dislike, via: :delete
  match '/favourites', to: "likes#index", as: :favourites, via: :get

  concern :attachable do
    resources :attachments, only: [:create, :destroy]
  end

  resources :attachments, only: [:index, :new, :show, :create, :destroy] do
    resources :reports, only: [:new]
  end

  match '/course/:course_code', as: :course, to: 'courses#show', via: :get 

  resources :courses, only: [:new, :index, :create], concerns: [:attachable] do
    resources :enrollments, only: [:create]
  end

  resources :enrollments, only: [:index, :destroy] 

  resources :guides, only: [:new, :index, :create, :edit, :show, :update, :destroy], concerns: [:attachable] do
    resources :reports, only: [:new]
  end

  resources :reports, only: [:new, :show, :create, :destroy]

resources :messages, only: [:create]
resources :conversations, only: [:index, :show, :destroy] do
  member do
    post :reply
    post :trash
    post :untrash
    post :mark_as_read
  end

  collection do 
    delete :empty_trash
  end
end

end

app/views/shared/_attachments.html.erb
<div class="row">
  <% attachments.each do |a| %>
    <div class="col-xs-4">
      <div class="card"> 
       
      <% if favourite %>  
        <div class="favourite">
          <% if liked?(a) %>
            <%= render 'shared/dislike_btn', resource: a %>
          <% else %>
            <%= render 'shared/like_btn', resource: a %>
          <% end %>
        </div> 
      <% end %>              
        <div class="card-image"> 
          <%= link_to attachment_icon_for(a), a %>
        </div>
        
        <div class="card-info">
          
          <div class="name">
            <p><%= link_to truncate(a.upload_file_name, length: 10),  a %></p> 
          </div>
          
          <hr>
          
          <div class="content">
            <p>
              <b>For <%= a.attachable_type.downcase %>:</b> 
              <% if a.attachable_type == "Course" %>  
                <%= link_to a.attachable.course_code, course_path(course_code: a.attachable.course_code) %>
              <% elsif a.attachable_type == "Guide" %>
                <%= link_to a.attachable.title, a.attachable %>
              <% end %>
              <br>
              <b>Uploader: </b> 
              <%= link_to a.user.username, user_path(username: a.user.username) unless a.user.nil? %>
            </p>
            <p data-no-turbolink><%= link_to download_path(id: a.id), class: 'btn btn-labeled btn-success' do %>
              <span class="btn-label"><i class="fa fa-download"></i>&nbsp;<%= a.download_count %></span>
              Download
            <% end %></p>
          
          </div>
        </div>
      </div>    
    </div>
  <% end %>
</div>

app/views/shared/_courses.html.erb
<% courses.each do |c| %>
  <div class="row">    
    <div class="col-xs-12">

      <div class="card">                

        <div class="card-image"> 
          <%= link_to (course_image c), course_path(course_code: c.course_code) %>
        </div>
        
        <div class="card-info">
          
          <div class="name">
            <p><%= link_to "#{c.course_code} | #{c.title}", course_path(course_code: c.course_code) %></p> 
          </div>
          
          <hr>
          
          <div class="content">
            <p>
              <b>Description:</b> 
              <%= c.description %>
            </p>
            <p><b>Enrollments:</b> <%= c.enrollments.count %></p>
          </div>
        </div>
      </div>    
    </div>
  </div>
<% end %>

app/views/shared/_dislike_btn.html.erb
  <%= link_to dislike_path(resource: resource.class.to_s.downcase, id: resource.id), class: 'dislike-btn', method: :delete, remote: true do %>
    <i class="fa fa-times" data-toggle="tooltip" title="Remove from favourites"></i>
  <% end %>

app/views/shared/_errors.html.erb
<% if record.errors.any? %>
  <div class="alert alert-warning fade in" id="<%=record.class.to_s.downcase%>_explanation">
    <h2><%= pluralize(record.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
    <% record.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <% unless message.blank? %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message.html_safe %>
  <% end %>
<% end %>

app/views/shared/_guides.html.erb
<div class="row"> 
  <% guides.each do |g| %>
   
    <div class="col-xs-12">

      <div class="card">                

        <div class="card-image"> 
          <%= link_to (course_image g.course), course_path(course_code: g.course.course_code) %>
        </div>
        
        <div class="card-info">
          
          <div class="name">
            <p><%= link_to truncate(g.title,length: 80), g %></p> 
          </div>
          
          <hr>
          
          <div class="content">
            <p>
              <b>Guide for:</b> 
              <%= g.course.course_code %>
            </p>
            <p><b>Attachments:</b> <%= g.attachments.count %></p>
          </div>
        </div>
      </div>    
    </div>
  <% end %>  
</div>

app/views/shared/_like_btn.html.erb
<%= link_to like_path(resource.class.to_s.downcase, id: resource.id), class: 'like-btn', method: :post, remote: true do %>
    <i class="fa fa-heart" data-toggle="tooltip" title="Add to favourites"></i>
<% end %>

app/views/shared/_new_report.html.erb
<div class="modal fade" id="new-report-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= "Create new report against this #{type.downcase}" %></h4>
      </div>
      <div class="modal-body">
        <div id="report-error-container">
          <%= render 'shared/errors', record: report %>  
        </div>
        <%= form_for report, remote: true do |f| %>

        <div class="input">
          <%= f.text_field :title, placeholder: 'Enter report title', id: 'title', required: true, autofocus: true %>
          <label for="title">Title</label>
          <span class="help-block">Keep it simple (you may elaborate below)</span>
        </div>

        <div class="input">
          <%= f.text_area :reason, placeholder: 'Please tell us why you are submitting the report', id: 'reason' %>
          <label for="reason">Reason</label>
          <%= f.hidden_field :reportable_type, value: type %>
          <%= f.hidden_field :reportable_id, value: reportable.id %>
        </div>
        
      </div>
      <div class="modal-footer">
        <%= f.submit 'Submit Report', class: 'btn btn-primary', id: 'report-submit'%>
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
        

app/views/shared/_users.html.erb
<div class="row">
  <% users.each do |u| %>
    <div class="col-xs-6">
      <div class="card">                
        <div class="card-image"> 
          <%= link_to gravatar_for(u, size: 150), user_path(username: u.username) %>
        </div>
        
        <div class="card-info">
          
          <div class="name">
            <p><%= link_to u.username, user_path(username: u.username) %></p> 
          </div>
          
          <hr>
          
          <div class="content">
            <p>
              <b>About <%= u.username %>:</b> 
              <% if u.about_me.blank? %>
                N/A
              <% else %>
                <%= truncate u.about_me, length: 200 %>
              <% end %> 

            </p>
            <p><b>Contributions:</b> <%= u.guides.size + u.attachments.size %></p>
          </div>
        </div>
      </div>    
    </div>
  <% end %>
</div>