config/routes.rb
Rails.application.routes.draw do
  
  root 'main_pages#home' #Root path

  match '/home',    to: 'main_pages#home',    via: :get
  match '/about',   to: 'main_pages#about',   via: :get
  match '/contact', to: 'main_pages#contact', via: :get
  match '/attachments/download/:id', to: 'attachments#download', via: :get, as: 'download'

  match '/admin_feed', to: 'main_pages#admin_feed', via: :get
  match '/user/ban/:id', to: 'users#ban', as: :ban, via: :post
  match '/unban/:id', to: 'users#unban', as: :unban, via: :get
  match '/user/remove/:id', to: 'users#destroy', as: :remove_user, via: :delete
  match 'approve/:resource/:id', to: 'application#approve', as: :approve, via: :patch

  match '/search', to: 'searches#search', via: :get 

  devise_for :users, :skip => [:sessions], controllers: {registrations: 'registrations'}
  resources :users, only: [:index]
  as :user do
    get '/signin' => 'devise/sessions#new', :as => :new_user_session
    post '/signin' => 'devise/sessions#create', :as => :user_session
    match '/signout' => 'devise/sessions#destroy', :as => :log_out, :via => :delete
    match '/signout' => 'devise/sessions#destroy', :via => :get
  end

  match '/user/:username', to: 'users#show', as: :user, via: :get
  

  resources :users, only: [:index] do
    resources :friend_requests, only: [:create]
  end

  resources :friend_requests, only: [:destroy]
  resources :friendships, only: [:index, :create, :destroy]

  match '/like/:resource/:id', to: "likes#create", as: :like, via: :post
  match '/dislike/:resource/:id', to: "likes#destroy", as: :dislike, via: :delete
  match '/favourites', to: "likes#index", as: :favourites, via: :get

  concern :attachable do
    resources :attachments, only: [:create, :destroy]
  end

  resources :attachments, only: [:index, :new, :show, :create, :destroy] do
    resources :reports, only: [:new]
  end

  match '/course/:course_code', as: :course, to: 'courses#show', via: :get 

  resources :courses, only: [:new, :index, :create], concerns: [:attachable] do
    resources :enrollments, only: [:create]
  end

  resources :enrollments, only: [:index, :destroy] 

  resources :guides, only: [:new, :index, :create, :edit, :show, :update, :destroy], concerns: [:attachable] do
    resources :reports, only: [:new]
  end

  resources :reports, only: [:new, :show, :create, :destroy]

resources :messages, only: [:create]
resources :conversations, only: [:index, :show, :destroy] do
  member do
    post :reply
    post :trash
    post :untrash
    post :mark_as_read
  end

  collection do 
    delete :empty_trash
  end
end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  before_action :authenticate_user!

  def new
    unless current_user.admin?
      flash[:error] = "You tried accessing a restricted area. You have been redirected."
      redirect_to root_path
    end
    @course = Course.new
  end

  def edit
    course
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:success] = "Course created"
      redirect_to course_path(course_code: @course.course_code)
    else
      flash[:error] = "Course: #{@course.course_code} was not saved properly"
      render 'new'
    end
  end

  def index
    if params[:q] 
      @courses = Course.search(params[:q]).page(params[:cpage]).per(10)
    else
      @courses = Course.all.page(params[:cpage]).per(10)
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    course
    @guide = @course.guides.build
    @attachment = @course.attachments.build
    @guides = @course.guides.where(approved: true).limit(3)
    @attachments = @course.attachments.approved.limit(6)
    @enrollment = @course.enrollments.where(user_id: current_user.id)
    # Find last few enrolled users for display
    @recently_enrolled_users = []
    @last_enrollments = @course.enrollments.order('updated_at DESC').limit(4)
    
    @last_enrollments.each do |e|
      @recently_enrolled_users << e.user 
    end

    respond_to do |format| 
      format.html 
      format.js
    end
  end

private

  def course
    @course = Course.find_by course_code: params[:course_code]
  end

  def course_params
    params.require(:course).permit(:id, :course_code, :title, :description)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper


end

app/views/courses/_courses.html.erb
<% @courses.each do |course| %>
  <h5><%= course.course_code %> | <%= course.title %><br></h5>
  <p>
    <%= course.description %>
  </p>
  <br>
<% end %>

app/views/courses/_new_attachment.html.erb
<div class="modal fade" id="new-attachment-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= "Add attachments for #{course.course_code}" %></h4>
      </div>
      <div class="modal-body">
        <div id="error-container">
          <%= render 'shared/errors', record: attachment %>  
        </div>
        <%= form_for attachment, remote: true, html: { multipart: true } do |f| %>
        
        <div class="input">
          <%= f.text_area :description, placeholder: 'Describe the attachment(s)', id: 'desc', rows: 4, required: true %>
          <label for="desc">Description</label>
        </div>

        <div class="control-group">
          <%= f.label :attachments, 'Attachment(s)', class: 'control-label' %>
          <div class="controls">
            <!-- ATTACHMENTS UPLOAD -->
            <%= file_field_tag "uploads[]", type: :file, multiple: true %>
          </div>
        </div>

        <%= f.hidden_field :attachable_type, value: "Course" %>
        <%= f.hidden_field :attachable_id, value: course.id %>
        
      </div>
      <div class="modal-footer">
        <%= f.submit 'Submit Attachment(s)', class: 'btn btn-primary', id: 'attachment-submit', remote: true %>
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
        

app/views/courses/_new_guide.html.erb
<div class="modal fade larger-modal" id="new-guide-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= "New Guide for #{course.course_code}" %></h4>
      </div>
      <div class="modal-body">
        <div id="guide-error-container">
          <%= render 'shared/errors', record: guide %>  
        </div>

        <%= form_for guide, remote: true, html: { multipart: true } do |f| %>
        <div class="input">
          <%= f.text_field :title, placeholder: "Enter the guide's title", id: 'title', class: 'text_field' %>
          <label for="title">Title</label>
        </div>
        <div class="control-group">
          <%= f.label :content, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_area :content, class: 'froala-textarea', id: 'guide-content' %>
          </div>
          <%= f.hidden_field :course_id, value: course.id %>
        </div>

        <div class="control-group">
          <%= f.label :attachments, :class => 'control-label' %>
          <div class="controls">
            <!-- GUIDE ATTACHMENTS UPLOAD -->
            <%= file_field_tag "uploads[]", type: :file, multiple: true %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit 'Submit Guide', class: 'btn btn-primary', id: 'guide-submit' %>
      </div>



      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
        

app/views/courses/index.html.erb
<div class="main-card">
  <h2>Courses</h2>
  <div class="search-wrapper">
    <% if @courses.any? %>
    <!-- COURSE RESULTS HERE -->
    <hr>
    <div class="c-pag">
      <center><%= paginate @courses, param_name: 'cpage', remote: true %></center>
    </div>
    <div id="search-courses">
      <%= render 'shared/courses', courses: @courses %>
    </div>
    <div class="c-pag">
      <center><%= paginate @courses, param_name: 'cpage', remote: true %></center>
    </div>
  <% end %>

  </div>
</div>

app/views/courses/index.js.erb
$(function(){
//-- Course AJAX pagination
<% if @courses.any? %>
  $('.c-pag').html("<center><%= j paginate @courses, remote: true, param_name: 'cpage' %></center>");
  $('#search-courses').html("<%= j render 'shared/courses', courses: @courses %>");
<% end %>
});

app/views/courses/new.html.erb
<% if !current_user.admin? %>
  <p>You do not have permission to view this page.</p>
<% else %>
  <h1>Create a Course (admins only)</h1>

  <%= simple_form_for @course do |f| %>
    <%= f.input :course_code %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.button :submit %>
  <% end %>
<% end %>

app/views/courses/show.html.erb
<div class="main-card" id="course-container">
 <hr>

  <div id="new-attachment-container">
    <%= render 'new_attachment', attachment: @attachment, course: @course %>
  </div>


<div class="row user-menu-container square">
        <div class="col-md-7 user-details">
            <div class="row bluebg">
                <div class="col-md-6 no-pad">
                    <div class="user-pad">
                        <h3><%= @course.course_code %> | <%= @course.title %></h3>
                        <br>
                      
                        <!-- NEW GUIDE BUTTON  -->
                        <button type="button" class="btn btn-labeled btn-success" id="new-guide-trigger">
                          <span class="btn-label"><i class="fa fa-pencil"></i></span>
                          New Guide
                        </button>
                      
                    </div>
                </div>
                <div class="col-md-6 no-pad">
                    <div class="course-image">
                      <%= course_image @course %>
                    </div>
                </div>
            </div>
            <div class="row overview">
                <div class="col-md-4 user-pad text-center">
                    <h3>ENROLLMENTS</h3>
                    <h4><%= @course.enrollments.count %></h4>
                </div>
                <div class="col-md-4 user-pad text-center">
                    <h3>GUIDES</h3>
                    <h4 id="guide-count"><%= @course.guides.approved.count %></h4>
                </div>
                <div class="col-md-4 user-pad text-center">
                    <h3>ATTACHMENTS</h3>
                    <h4 id="attachment-count"><%= @course.attachments.approved.count %></h4>
                </div>
            </div>
        </div>
        <div class="col-md-1 user-menu-btns">
            <div class="btn-group-vertical square" id="responsive">
                <a href="#" class="btn btn-block btn-default active">
                  <i class="fa fa-graduation-cap fa-3x"></i>
                </a>
                <a href="#" class="btn btn-default">
                  <i class="fa fa-file-text-o fa-3x"></i>
                </a>
                <a href="#" class="btn btn-default">
                  <i class="fa fa-paperclip fa-3x"></i>
                </a>
                <a href="#" class="btn btn-default">
                  <i class="fa fa-cloud-upload fa-3x"></i>
                </a>
            </div>
        </div>
        <div class="col-md-4 user-menu user-pad">
            <div class="user-menu-content active">
                <h3>
                    Recently Enrolled Users
                </h3>
                <ul class="user-menu-list">

                  <% @recently_enrolled_users.each do |u| %>
                    <li>
                      <h4>
                        <%= link_to u.username, user_path(username: u.username) %>
                      </h4>
                    </li>
                  <% end %>

                    <li>
                    <% if user_signed_in? && !(current_user.courses.include? @course) %>
                      <%= link_to course_enrollments_path(course_id: @course.id), class: 'btn btn-labeled btn-success',method: :post do %>
                        <span class="btn-label"><i class="fa fa-plus"></i></span>
                        Enroll
                      <% end %>
                   
                    <% else %>
                      <%= link_to enrollment_path(id: @enrollment[0].id, from_course: @course.course_code), class: 'btn btn-labeled btn-danger',method: :delete do %>
                        <span class="btn-label"><i class="fa fa-times"></i></span>
                        Un-enroll
                      <% end %>
                    <% end %>
                    </li>
                </ul>
            </div>
            <div class="user-menu-content">
                <h3>
                  Recent Guides for <%= @course.course_code %>
                </h3>
                <ul class="user-menu-list">
                  <% if @guides.any? %>
                    <% @guides.each do |g| %>
                      <li>
                        <h4><%= link_to truncate(g.title, length: 40), g %></h4>
                        <% unless g.user.nil? %>
                          by: <%= link_to truncate("#{g.user.username}", length: 40), user_path(username: g.user.username) %>
                        <% end %>  
                      </li>
                    <% end %>  
                    <li>
                      <%= link_to guides_path(for_course: @course.id), class: 'btn btn-labeled btn-success' do %>
                        <span class="btn-label"><i class="fa fa-external-link"></i></span>
                        View all
                      <% end %>  
                    </li>
                  <% else %>
                    <p>No guides have been written and/or approved yet. </p>
                  <% end %>  
                    <li>
                        
                      
                    </li>
                </ul>
            </div>
            <div class="user-menu-content">
                <h3>
                  Recently approved attachments 
                </h3>
                
                <ul class="user-menu-list">
                  <% if @attachments.any? %>
                    <% @attachments.each do |a| %>
                      <li class="col-xs-4">
                        
                        <div class="info attachment-info">
                          
                            <p>
                              <%= attachment_icon_for a %>
                              <%= link_to (truncate a.upload_file_name, length: 12), a  %> 
                            </p>
             
                        </div>
                        <div class="stats bluebg">
                          <span class="fa fa-heart-o"> <strong><%= a.likes.count %></strong></span>
                          <span class="fa fa-download pull-right"> <strong><%= a.download_count %></strong></span>
                        </div>
                  
                      </li>
                    <% end %>  
                    <li>
                      <%= link_to attachments_path(for_course: @course.course_code), class: 'btn btn-labeled btn-success' do %>
                        <span class="btn-label"><i class="fa fa-external-link"></i></span>
                        View all
                      <% end %>  
                    </li>
                  <% else %>
                    <p>No attachments for <%= @course.course_code %> have been approved yet. </p>
                  <% end %>  
                    <li>
                        
                      
                    </li>
                </ul>

                
            </div>
            <div class="user-menu-content">
                <h2 class="text-center">
                    Start Sharing!
                </h2>
                <center><i class="fa fa-cloud-upload fa-4x"></i></center>
                <div class="share-links">
                  <center>
                    <button type="button" class="btn btn-lg btn-labeled btn-success" id="new-attachment-trigger" style="margin-bottom: 15px;">
                      <span class="btn-label"><i class="fa fa-upload"></i></span>
                      Upload <%= @course.course_code%> Resource
                    </button>
                  </center>
                </div>
            </div>
        </div>
        <div class="col-lg-6" id="course-description">
  <p><%= @course.description %></p>  
</div>

    </div>



<div class="col-lg-12"><hr><br></div>


</div>  

  <!-- RENDER NEW GUIDE MODAL HERE -->
<div id="new-guide-container">
    <%= render 'new_guide', guide: @guide, course: @course %>
</div>